services:
  postgresql:
    image: docker.io/library/postgres:15.1@sha256:10d6e725f9b2f5531617d93164f4fc85b1739e04cab62cbfbfb81ccd866513b8
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 1g
    ipc: private
    security_opt:
      - "no-new-privileges:true"
    privileged: false
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vfps
    ports:
      - "127.0.0.1:35432:5432"

  jaeger:
    image: docker.io/jaegertracing/all-in-one:1.39.0@sha256:2c610c909455dfd7eaa0361873e85a8a518c2e837f8800519b9798282439c998
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 1g
    cap_drop:
      - ALL
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    privileged: false
    profiles:
      - jaeger
    ports:
      - "6831:6831/udp"
      - "127.0.0.1:16686:16686"

  vfps:
    image: ghcr.io/miracum/vfps:${VFPS_IMAGE_TAG:-v1.1.2} # x-release-please-version
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128m
          cpus: "1"
        reservations:
          memory: 128m
          cpus: "1"
    ipc: none
    cap_drop:
      - ALL
    read_only: true
    privileged: false
    security_opt:
      - "no-new-privileges:true"
    profiles:
      - test
    environment:
      COMPlus_EnableDiagnostics: "0"
      ForceRunDatabaseMigrations: "true"
      ConnectionStrings__PostgreSQL: "Host=postgresql:5432;Database=vfps;Timeout=60;Max Auto Prepare=5;Application Name=vfps;Maximum Pool Size=50;"
      PGUSER: postgres
      PGPASSWORD: postgres
    ports:
      # Http1, Http2, Http3
      - "127.0.0.1:8080:8080"
      # Http2-only for plaintext gRPC
      - "127.0.0.1:8081:8081"
