services:
  postgresql:
    image: docker.io/library/postgres:17.0@sha256:4ec37d2a07a0067f176fdcc9d4bb633a5724d2cc4f892c7a2046d054bb6939e5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 1g
    ipc: private
    security_opt:
      - "no-new-privileges:true"
    privileged: false
    environment:
      # kics-scan ignore-line
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vfps
    ports:
      - "127.0.0.1:35432:5432"

  jaeger:
    image: docker.io/jaegertracing/all-in-one:1.59.0@sha256:e369bd9a8e4a212bfed67aaff59b77ce0676df32828aaccca468a866efcb732b
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 1g
    cap_drop:
      - ALL
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    privileged: false
    profiles:
      - jaeger
    ports:
      - "6831:6831/udp"
      - "127.0.0.1:16686:16686"

  vfps:
    image: ghcr.io/miracum/vfps:${VFPS_IMAGE_TAG:-v1.3.5} # x-release-please-version
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128m
          cpus: "1"
        reservations:
          memory: 128m
          cpus: "1"
    ipc: none
    cap_drop:
      - ALL
    read_only: true
    privileged: false
    security_opt:
      - "no-new-privileges:true"
    profiles:
      - test
    environment:
      COMPlus_EnableDiagnostics: "0"
      ForceRunDatabaseMigrations: "true"
      ConnectionStrings__PostgreSQL: "Host=postgresql:5432;Database=vfps;Timeout=60;Max Auto Prepare=5;Application Name=vfps;Maximum Pool Size=50;"
      PGUSER: postgres
      # kics-scan ignore-line
      PGPASSWORD: postgres
    ports:
      # Http1, Http2, Http3
      - "127.0.0.1:8080:8080"
      # Http2-only for plaintext gRPC
      - "127.0.0.1:8081:8081"
