name: benchmarks

on:
  push:
    tags:
      - "v*"
    branches: [master]
    paths:
      - src/**
  pull_request:
    branches: [master]
    paths:
      - src/**

# Declare default permissions as read only.
permissions: read-all

jobs:
  benchmark:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pages: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4.0.1
        with:
          dotnet-version: "8.0.x"

      - name: Run benchmark
        run: dotnet run -c Release --project=src/Vfps.Benchmarks

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@4de1bed97a47495fc4c5404952da0499e31f5c29 # v1.20.3
        with:
          name: PseudonymGeneratorBenchmarks
          tool: "benchmarkdotnet"
          output-file-path: BenchmarkDotNet.Artifacts/results/Vfps.Benchmarks.PseudonymGeneratorBenchmarks-report-full-compressed.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: ${{github.event_name != 'pull_request'}}
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: "200%"
          comment-on-alert: true
          fail-on-alert: true
