name: benchmarks

on:
  push:
    tags:
      - "v*"
    branches: [master]
    paths:
      - src/**
  pull_request:
    branches: [master]
    paths:
      - src/**

# Declare default permissions as read only.
permissions: read-all

jobs:
  benchmark:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pages: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4.0.0
        with:
          dotnet-version: "8.0.x"

      - name: Run benchmark
        run: dotnet run -c Release --project=src/Vfps.Benchmarks

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@cc9ac13ce81036c9b67fcfe2cb95ca366684b9ea # v1.19.3
        with:
          name: PseudonymGeneratorBenchmarks
          tool: "benchmarkdotnet"
          output-file-path: BenchmarkDotNet.Artifacts/results/Vfps.Benchmarks.PseudonymGeneratorBenchmarks-report-full-compressed.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: ${{github.event_name != 'pull_request'}}
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: "200%"
          comment-on-alert: true
          fail-on-alert: true
