name: buf

on:
  pull_request:
    branches: [master]

# Declare default permissions as read only.
permissions: read-all

jobs:
  lint:
    name: lint
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: bufbuild/buf-setup-action@2881ede27923557cb71f4ddc8954905c2639d1fb # v1.41.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: check formatting
        working-directory: src/Vfps
        run: buf format --exit-code

      - uses: bufbuild/buf-lint-action@06f9dd823d873146471cfaaf108a993fe00e5325 # v1.1.1
        with:
          input: src/Vfps
      # Doesn't currently work due to the weird file setup. Fails with:
      # Error: Protos/vfps/api/v1/meta.proto: does not exist
      # Error: Protos/vfps/api/v1/meta.proto: does not exist
      # Error: google/api/http.proto: does not exist
      # Error: buf found 3 breaking changes.
      # - uses: bufbuild/buf-breaking-action@1cd949a5f7c5581990772f1e0c8a5270d7e4401b # tag=v1.1.1
      #   with:
      #     input: src/Vfps
      #     against: "https://github.com/${{ github.repository }}.git#branch=master"
