name: nightly chaos testing

on:
  workflow_dispatch: {}
  schedule:
    # daily at 04:07
    - cron: "07 04 * * *"

# Declare default permissions as read only.
permissions: read-all

jobs:
  chaos-testing:
    name: chaos testing
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3

      - name: Install Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run chaos-test task
        run: task chaos-test

      - name: Print cluster logs
        if: always()
        run: |
          kubectl cluster-info dump -o yaml | tee kind-cluster-dump.txt

      - name: Upload cluster dump
        if: always()
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: kind-cluster-dump.txt
          path: |
            kind-cluster-dump.txt
